name: vault
description: A simple, secure offline password manager.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  go_router: ^13.2.0
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  cryptography: ^2.7.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
